name: Deploy VitePress site to Pages
on:
  workflow_dispatch: {}
  push:
    branches: [github-pages]

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build with VitePress
        run: pnpm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist
  # 工作流的名称
  deploy:
    needs: build # 这指定了此部署任务依赖于另一个名为build的任务。确保在开始部署之前完成了构建任务。

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Deploy with gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages

      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Setup Pages
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: npm
      # - run: npm ci
      # - name: Build
      #   run: npm run docs:build
      # - uses: actions/configure-pages@v3
      # - uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: docs/.vitepress/dist
      # - name: Deploy
      #   id: deployment
      #   uses: actions/deploy-pages@v1
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.ACCESS_TOKEN }}
      #     publish_dir: docs/.vitepress/dist
