name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build with VitePress
        run: npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        id: deployment
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: docs/.vitepress/dist
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Setup Pages
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: npm
      # - run: npm ci
      # - name: Build
      #   run: npm run docs:build
      # - uses: actions/configure-pages@v3
      # - uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: docs/.vitepress/dist
      # - name: Deploy
      #   id: deployment
      #   uses: actions/deploy-pages@v1
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.ACCESS_TOKEN }}
      #     publish_dir: docs/.vitepress/dist
